server:
  port: ${PORT:8060}

eureka:
  instance:
    hostname: api-gateway-02785a509cc8.herokuapp.com
  client:
    serviceUrl:
      defaultZone: https://service-registry-668227fe367b.herokuapp.com/eureka/
     
management:
  zipkin:
    tracing:
      endpoint: https://zipkin-c57be76182bd.herokuapp.com/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: EMPLOYEE-SERVICE
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employee/**
        - id: BACKOFFICE-SERVICE
          uri: lb://BACKOFFICE-SERVICE
          predicates:
            - Path=/backoffice/**

logging:
  level:
    org.springframework.cloud.gateway: TRACE
