server:
  port: ${PORT:8060}

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: https://service-registry-668227fe367b.herokuapp.com/eureka

management:
  zipkin:
    tracing:
      endpoint: https://zipkin-c57be76182bd.herokuapp.com/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:https://configuration-service-6d7884366eca.herokuapp.com/"
  cloud:
    discovery:
      enabled: true
    gateway:
      default-filters:
        - StripPrefix=1
      routes:
        - id: employee-service
          uri: lb://employee-service/
          predicates:
            - Path=/employee/**
        - id: backoffice-service
          uri: lb://backoffice-service/
          predicates:
            - Path=/backoffice/**
