server:
  port: ${PORT:8060}

eureka:
  client:
    serviceUrl:
      defaultZone: service-registry-668227fe367b.herokuapp.com/eureka

management:
  zipkin:
    tracing:
      endpoint: zipkin-c57be76182bd.herokuapp.com/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:configuration-service-6d7884366eca.herokuapp.com/"
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service/
          predicates:
            - Path=/employee/**
        - id: backoffice-service
          uri: lb://backoffice-service/
          predicates:
            - Path=/backoffice/**
